"""add index on jobs.created_at

Revision ID: f74975c08dfb
Revises: f772387260f6
Create Date: 2026-04-21 15:14:40.462165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision utilisés par Alembic.
revision: str = 'f74975c08dfb'
down_revision: Union[str, None] = 'f772387260f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Applique la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annule la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    # ### end Alembic commands ###
