"""add gpu_run_id to jobs

Revision ID: 2d16d2b3d56d
Revises: a3170125848e
Create Date: 2026-04-22 16:13:20.197133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision utilisés par Alembic.
revision: str = '2d16d2b3d56d'
down_revision: Union[str, None] = 'a3170125848e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Applique la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('gpu_run_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annule la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'gpu_run_id')
    # ### end Alembic commands ###
