apiVersion: v1
kind: Service
metadata:
  name: {{ include "gegm-upscaler.fullname" . }}-api
  labels:
    {{- include "gegm-upscaler.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gegm-upscaler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
