{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gegm-upscaler.serviceAccountName" . }}
  labels:
    {{- include "gegm-upscaler.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    # Annotations d'auth Vault Kubernetes — le role Vault doit être créé
    # côté infra et mappé sur ce ServiceAccount (namespace + name).
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
